### ISSUE TITLE
Stable release version

### ISSUE THREAD

**Issue by maheshjena1** [go-zepto/zepto#2]
Hi,
The project seems to be very active with continuous development.
Is there any stable release (latest version) that we can start using?

Regards,
Mahesh

**Comment by carlosstrand** [comment]
Hello, @maheshjena1! Thanks for your interest and sorry for the delay in responding. The latest version v0.0.8 is very complete and you can create a full web project.

If you have any questions or suggestions, don't hesitate to ask.

Thanks!
